version: "3.3"

services:
  app:
    image: jadilsonpaiva/nodeapp
    ports:
      - 80:3000
    #working_dir: /app
    #volumes:
    #  - /root/nodeapp:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    volumes:
      - /root/nodeapp/banco/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

